/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** @type object */
export interface AssetClass {
  /**
   * @description Format: `uuid`
   *
   * @example
   *   550e8400-e29b-41d4-a716-446655440000
   *
   * @type string
   */
  id: string;
  /**
   * @example
   *   Equities;
   * @type string
   */
  name: string;
  /**
   * @example
   *   Stocks and equity securities
   * @type string | undefined
   */
  description?: string | null;
  /**
   * @description Format: `date-time`
   *
   * @example
   *   2026-07-30T12:00:00Z
   *
   * @type string
   */
  createdAt: string;
  /**
   * @description Format: `date-time`
   *
   * @example
   *   2026-07-30T12:00:00Z
   *
   * @type string
   */
  updatedAt: string;
}
