/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface AssetClassInput {
  /**
   * @type string
   * @minLength 1
   */
  name: string;
  /** @type string | undefined */
  description?: string;
}
