/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface AssetClass {
  /** @type string, uuid */
  id: string;
  /**
   * @type string
   * @minLength 1
   */
  name: string;
  /** @type string */
  description: string;
}
