/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** @type object */
export interface CreateAssetClassRequest {
  /**
   * @example
   *   Equities;
   * @type string
   */
  name: string;
  /**
   * @example
   *   Stocks and equity securities
   * @type string | undefined
   */
  description?: string | null;
}
