/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { AssetClass } from "./AssetClass.ts";
import type { CreateAssetClassRequest } from "./CreateAssetClassRequest.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";
import type { ValidationErrors } from "./ValidationErrors.ts";

/** @type object */
export type CreateAssetClassStatus201 = AssetClass;

/** @type object */
export type CreateAssetClassStatus401 = ErrorResponse;

/** @type object */
export type CreateAssetClassStatus422 = ValidationErrors;

/** @type object */
export type CreateAssetClassData = CreateAssetClassRequest;

/** @type object */
export interface CreateAssetClassRequestConfig {
  body: CreateAssetClassData;
  path?: never;
  query?: never;
  headers?: never;
}

/** @type object */
export interface CreateAssetClassResponses {
  "201": CreateAssetClassStatus201;
  "401": CreateAssetClassStatus401;
  "422": CreateAssetClassStatus422;
}

/** @description Union of all possible responses. */
export type CreateAssetClassResponse =
  | CreateAssetClassStatus201
  | CreateAssetClassStatus401
  | CreateAssetClassStatus422;
