/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { AssetClass } from "./AssetClass.ts";
import type { AssetClassInput } from "./AssetClassInput.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";
import type { ValidationErrors } from "./ValidationErrors.ts";

/** @description Asset class created. */
export type CreateAsset201 = AssetClass;

/** @description Unauthorized — no valid session. */
export type CreateAsset401 = ErrorResponse;

/** @description Unprocessable entity — validation error. */
export type CreateAsset422 = ValidationErrors;

export type CreateAssetMutationRequest = AssetClassInput;

export type CreateAssetMutationResponse = CreateAsset201;

export interface CreateAssetMutation {
  Response: CreateAsset201;
  Request: CreateAssetMutationRequest;
  Errors: CreateAsset401 | CreateAsset422;
}
