/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { CurrentUserResponse } from "./CurrentUserResponse.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";

/** @description Current user info. */
export type CurrentUser200 = CurrentUserResponse;

/** @description Unauthorized — no valid session. */
export type CurrentUser401 = ErrorResponse;

export type CurrentUserQueryResponse = CurrentUser200;

export interface CurrentUserQuery {
  Response: CurrentUser200;
  Errors: CurrentUser401;
}
