/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface CurrentUserResponse {
  /** @type string, uuid */
  id: string;
  /** @type string, email */
  email: string;
}
