/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** @type object */
export interface CurrentUserResponse {
  /**
   * @description Format: `uuid`
   *
   * @example
   *   550e8400-e29b-41d4-a716-446655440000
   *
   * @type string
   */
  id: string;
  /**
   * @description Format: `email`
   *
   * @example
   *   user@example.com
   *
   * @type string
   */
  email: string;
}
