/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { CurrentUserResponse } from "./CurrentUserResponse.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";

/** @type object */
export type CurrentUserStatus200 = CurrentUserResponse;

/** @type object */
export type CurrentUserStatus401 = ErrorResponse;

/** @type object */
export interface CurrentUserRequestConfig {
  body?: never;
  path?: never;
  query?: never;
  headers?: never;
}

/** @type object */
export interface CurrentUserResponses {
  "200": CurrentUserStatus200;
  "401": CurrentUserStatus401;
}
