/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { ErrorResponse } from "./ErrorResponse.ts";

/**
 * @description Format: `uuid`
 *
 * @type string
 */
export type DeleteAssetClassPathId = string;

/** @type any */
export type DeleteAssetClassStatus204 = any;

/** @type object */
export type DeleteAssetClassStatus401 = ErrorResponse;

/** @type object */
export type DeleteAssetClassStatus404 = ErrorResponse;

/** @type object */
export interface DeleteAssetClassRequestConfig {
  body?: never;
  /** @type object */
  path: {
    id: DeleteAssetClassPathId;
  };
  query?: never;
  headers?: never;
}

/** @type object */
export interface DeleteAssetClassResponses {
  "204": DeleteAssetClassStatus204;
  "401": DeleteAssetClassStatus401;
  "404": DeleteAssetClassStatus404;
}

/** @description Union of all possible responses. */
export type DeleteAssetClassResponse =
  | DeleteAssetClassStatus204
  | DeleteAssetClassStatus401;
