/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { ErrorResponse } from "./ErrorResponse.ts";

export interface DeleteAssetPathParams {
  /** @type string, uuid */
  id: string;
}

/** @description Asset class deleted. */
export type DeleteAsset204 = any;

/** @description Unauthorized — no valid session. */
export type DeleteAsset401 = ErrorResponse;

/** @description Not found — no asset class with this ID. */
export type DeleteAsset404 = ErrorResponse;

export type DeleteAssetMutationResponse = DeleteAsset204;

export interface DeleteAssetMutation {
  Response: DeleteAsset204;
  PathParams: DeleteAssetPathParams;
  Errors: DeleteAsset401;
}
