/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** @type object */
export interface ErrorResponse {
  /**
   * @example
   *   email already registered
   * @type string
   */
  message: string;
}
