/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { AssetClass } from "./AssetClass.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";

/**
 * @description Format: `uuid`
 *
 * @type string
 */
export type GetAssetClassPathId = string;

/** @type object */
export type GetAssetClassStatus200 = AssetClass;

/** @type object */
export type GetAssetClassStatus401 = ErrorResponse;

/** @type object */
export type GetAssetClassStatus404 = ErrorResponse;

/** @type object */
export interface GetAssetClassRequestConfig {
  body?: never;
  /** @type object */
  path: {
    id: GetAssetClassPathId;
  };
  query?: never;
  headers?: never;
}

/** @type object */
export interface GetAssetClassResponses {
  "200": GetAssetClassStatus200;
  "401": GetAssetClassStatus401;
  "404": GetAssetClassStatus404;
}

/** @description Union of all possible responses. */
export type GetAssetClassResponse =
  | GetAssetClassStatus200
  | GetAssetClassStatus401;
