/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { AssetClass } from "./AssetClass.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";

export interface GetAssetPathParams {
  /** @type string, uuid */
  id: string;
}

/** @description OK. */
export type GetAsset200 = AssetClass;

/** @description Unauthorized — no valid session. */
export type GetAsset401 = ErrorResponse;

/** @description Not found — no asset class with this ID. */
export type GetAsset404 = ErrorResponse;

export type GetAssetQueryResponse = GetAsset200;

export interface GetAssetQuery {
  Response: GetAsset200;
  PathParams: GetAssetPathParams;
  Errors: GetAsset401;
}
