/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { ErrorResponse } from "./ErrorResponse.ts";
import type { UserResponse } from "./UserResponse.ts";

/** @type object */
export type GetCurrentUserStatus200 = UserResponse;

/** @type object */
export type GetCurrentUserStatus401 = ErrorResponse;

/** @type object */
export interface GetCurrentUserRequestConfig {
  body?: never;
  path?: never;
  query?: never;
  headers?: never;
}

/** @type object */
export interface GetCurrentUserResponses {
  "200": GetCurrentUserStatus200;
  "401": GetCurrentUserStatus401;
}

/** @description Union of all possible responses. */
export type GetCurrentUserResponse =
  | GetCurrentUserStatus200
  | GetCurrentUserStatus401;
