/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { AssetClass } from "./AssetClass.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";

/** @description OK. */
export type ListAssets200 = AssetClass[];

/** @description Unauthorized — no valid session. */
export type ListAssets401 = ErrorResponse;

export type ListAssetsQueryResponse = ListAssets200;

export interface ListAssetsQuery {
  Response: ListAssets200;
  Errors: ListAssets401;
}
