/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { ErrorResponse } from "./ErrorResponse.ts";
import type { LoginRequest } from "./LoginRequest.ts";
import type { LoginResponse } from "./LoginResponse.ts";
import type { ValidationErrors } from "./ValidationErrors.ts";

/** @description Authentication successful. */
export type Login200 = LoginResponse;

/** @description Unauthorized — invalid email or password. */
export type Login401 = ErrorResponse;

/** @description Unprocessable entity — validation error. */
export type Login422 = ValidationErrors;

export type LoginMutationRequest = LoginRequest;

export type LoginMutationResponse = Login200;

export interface LoginMutation {
  Response: Login200;
  Request: LoginMutationRequest;
  Errors: Login401 | Login422;
}
