/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface LoginRequest {
  /** @type string, email */
  email: string;
  /**
   * @type string
   * @minLength 8
   */
  password: string;
}
