/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { ErrorResponse } from "./ErrorResponse.ts";
import type { LoginRequest } from "./LoginRequest.ts";
import type { LoginResponse } from "./LoginResponse.ts";
import type { ValidationErrors } from "./ValidationErrors.ts";

/** @type object */
export type LoginStatus200 = LoginResponse;

/** @type object */
export type LoginStatus401 = ErrorResponse;

/** @type object */
export type LoginStatus422 = ValidationErrors;

/** @type object */
export type LoginData = LoginRequest;

/** @type object */
export interface LoginRequestConfig {
  body: LoginData;
  path?: never;
  query?: never;
  headers?: never;
}

/** @type object */
export interface LoginResponses {
  "200": LoginStatus200;
  "401": LoginStatus401;
  "422": LoginStatus422;
}
