/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** @description Logged out successfully. */
export type Logout204 = any;

export type LogoutMutationResponse = Logout204;

export interface LogoutMutation {
  Response: Logout204;
  Errors: any;
}
