/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** @type any */
export type LogoutStatus204 = any;

/** @type object */
export interface LogoutRequestConfig {
  body?: never;
  path?: never;
  query?: never;
  headers?: never;
}

/** @type object */
export interface LogoutResponses {
  "204": LogoutStatus204;
}

/** @description Union of all possible responses. */
export type LogoutResponse = LogoutStatus204;
