/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { PingResponse } from "./PingResponse.ts";

/** @type object */
export type PingStatus200 = PingResponse;

/** @type object */
export interface PingRequestConfig {
  body?: never;
  path?: never;
  query?: never;
  headers?: never;
}

/** @type object */
export interface PingResponses {
  "200": PingStatus200;
}
