/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { PingResponse } from "./PingResponse.ts";

/** @description OK. */
export type Ping200 = PingResponse;

export type PingQueryResponse = Ping200;

export interface PingQuery {
  Response: Ping200;
  Errors: any;
}
