/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** @type object */
export interface PingResponse {
  /**
   * @example
   *   ok;
   * @type string
   */
  status: string;
}
