/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { ErrorResponse } from "./ErrorResponse.ts";
import type { RegisterRequest } from "./RegisterRequest.ts";
import type { RegisterResponse } from "./RegisterResponse.ts";
import type { ValidationErrors } from "./ValidationErrors.ts";

/** @description User created and authenticated. */
export type Register201 = RegisterResponse;

/** @description Conflict — email already registered. */
export type Register409 = ErrorResponse;

/** @description Unprocessable entity — validation error. */
export type Register422 = ValidationErrors;

export type RegisterMutationRequest = RegisterRequest;

export type RegisterMutationResponse = Register201;

export interface RegisterMutation {
  Response: Register201;
  Request: RegisterMutationRequest;
  Errors: Register409 | Register422;
}
