/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** @type object */
export interface RegisterRequest {
  /**
   * @description Format: `email`
   *
   * @example
   *   user@example.com
   *
   * @type string
   */
  email: string;
  /**
   * @example
   *   secureP@ss123
   * @type string
   * @minLength 8
   */
  password: string;
}
