/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { SystemStatusResponse } from "./SystemStatusResponse.ts";

/** @description OK. */
export type SystemStatus200 = SystemStatusResponse;

export type SystemStatusQueryResponse = SystemStatus200;

export interface SystemStatusQuery {
  Response: SystemStatus200;
  Errors: any;
}
