/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface SystemStatusResponse {
  /**
   * @description Whether the system needs initial setup. True when no users exist.
   *
   * @type boolean
   */
  needsSetup: boolean;
}
