/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { AssetClass } from "./AssetClass.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";
import type { UpdateAssetClassRequest } from "./UpdateAssetClassRequest.ts";
import type { ValidationErrors } from "./ValidationErrors.ts";

/**
 * @description Format: `uuid`
 *
 * @type string
 */
export type UpdateAssetClassPathId = string;

/** @type object */
export type UpdateAssetClassStatus200 = AssetClass;

/** @type object */
export type UpdateAssetClassStatus401 = ErrorResponse;

/** @type object */
export type UpdateAssetClassStatus404 = ErrorResponse;

/** @type object */
export type UpdateAssetClassStatus422 = ValidationErrors;

/** @type object */
export type UpdateAssetClassData = UpdateAssetClassRequest;

/** @type object */
export interface UpdateAssetClassRequestConfig {
  body: UpdateAssetClassData;
  /** @type object */
  path: {
    id: UpdateAssetClassPathId;
  };
  query?: never;
  headers?: never;
}

/** @type object */
export interface UpdateAssetClassResponses {
  "200": UpdateAssetClassStatus200;
  "401": UpdateAssetClassStatus401;
  "404": UpdateAssetClassStatus404;
  "422": UpdateAssetClassStatus422;
}

/** @description Union of all possible responses. */
export type UpdateAssetClassResponse =
  | UpdateAssetClassStatus200
  | UpdateAssetClassStatus401
  | UpdateAssetClassStatus422;
