/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** @type object */
export interface UpdateAssetClassRequest {
  /**
   * @example
   *   Fixed Income
   * @type string | undefined
   */
  name?: string;
  /**
   * @example
   *   Bonds and debt securities
   * @type string | undefined
   */
  description?: string | null;
}
