/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { AssetClass } from "./AssetClass.ts";
import type { AssetClassInput } from "./AssetClassInput.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";
import type { ValidationErrors } from "./ValidationErrors.ts";

export interface UpdateAssetPathParams {
  /** @type string, uuid */
  id: string;
}

/** @description Asset class updated. */
export type UpdateAsset200 = AssetClass;

/** @description Unauthorized — no valid session. */
export type UpdateAsset401 = ErrorResponse;

/** @description Not found — no asset class with this ID. */
export type UpdateAsset404 = ErrorResponse;

/** @description Unprocessable entity — validation error. */
export type UpdateAsset422 = ValidationErrors;

export type UpdateAssetMutationRequest = AssetClassInput;

export type UpdateAssetMutationResponse = UpdateAsset200;

export interface UpdateAssetMutation {
  Response: UpdateAsset200;
  Request: UpdateAssetMutationRequest;
  PathParams: UpdateAssetPathParams;
  Errors: UpdateAsset401 | UpdateAsset422;
}
