/** @description Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { ValidationError } from "./ValidationError.ts";

/** @type object */
export interface ValidationErrors {
  /** @type array */
  errors: ValidationError[];
}
