// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_class.sql

package repository

import (
	"context"
	"database/sql"
)

const createAssetClass = `-- name: CreateAssetClass :exec
INSERT INTO asset_classes (id, name, description)
VALUES (?, ?, ?)
`

type CreateAssetClassParams struct {
	ID          string
	Name        string
	Description sql.NullString
}

// CreateAssetClass
//
//	INSERT INTO asset_classes (id, name, description)
//	VALUES (?, ?, ?)
func (q *Queries) CreateAssetClass(ctx context.Context, arg CreateAssetClassParams) error {
	_, err := q.db.ExecContext(ctx, createAssetClass, arg.ID, arg.Name, arg.Description)
	return err
}

const deleteAssetClass = `-- name: DeleteAssetClass :one
DELETE FROM asset_classes
WHERE id = ?
RETURNING id
`

// DeleteAssetClass
//
//	DELETE FROM asset_classes
//	WHERE id = ?
//	RETURNING id
func (q *Queries) DeleteAssetClass(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteAssetClass, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const findAssetClassByID = `-- name: FindAssetClassByID :one
SELECT id, name, description
FROM asset_classes
WHERE id = ?
LIMIT 1
`

// FindAssetClassByID
//
//	SELECT id, name, description
//	FROM asset_classes
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) FindAssetClassByID(ctx context.Context, id string) (AssetClass, error) {
	row := q.db.QueryRowContext(ctx, findAssetClassByID, id)
	var i AssetClass
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const findAssetClassByName = `-- name: FindAssetClassByName :one
SELECT id, name, description
FROM asset_classes
WHERE name = ?
LIMIT 1
`

// FindAssetClassByName
//
//	SELECT id, name, description
//	FROM asset_classes
//	WHERE name = ?
//	LIMIT 1
func (q *Queries) FindAssetClassByName(ctx context.Context, name string) (AssetClass, error) {
	row := q.db.QueryRowContext(ctx, findAssetClassByName, name)
	var i AssetClass
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listAssetClasses = `-- name: ListAssetClasses :many
SELECT id, name, description
FROM asset_classes
ORDER BY name COLLATE NOCASE ASC
`

// ListAssetClasses
//
//	SELECT id, name, description
//	FROM asset_classes
//	ORDER BY name COLLATE NOCASE ASC
func (q *Queries) ListAssetClasses(ctx context.Context) ([]AssetClass, error) {
	rows, err := q.db.QueryContext(ctx, listAssetClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetClass
	for rows.Next() {
		var i AssetClass
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetClass = `-- name: UpdateAssetClass :one
UPDATE asset_classes
SET name = ?, description = ?
WHERE id = ?
RETURNING id, name, description
`

type UpdateAssetClassParams struct {
	Name        string
	Description sql.NullString
	ID          string
}

// UpdateAssetClass
//
//	UPDATE asset_classes
//	SET name = ?, description = ?
//	WHERE id = ?
//	RETURNING id, name, description
func (q *Queries) UpdateAssetClass(ctx context.Context, arg UpdateAssetClassParams) (AssetClass, error) {
	row := q.db.QueryRowContext(ctx, updateAssetClass, arg.Name, arg.Description, arg.ID)
	var i AssetClass
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
