// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string `json:"-"`
}
