// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

type AssetClass struct {
	ID          string
	Name        string
	Description interface{}
}

type User struct {
	ID           string
	Email        string
	PasswordHash string `json:"-"`
}
