// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
)

type AssetClass struct {
	ID          string
	Name        string
	Description sql.NullString
}

type User struct {
	ID           string
	Email        string
	PasswordHash string `json:"-"`
}
