// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	FindUserByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
