version: "2"

linters:
  default: all
  disable:
    - wsl
    - gomodguard
    - exhaustruct
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - .*ResponseObject$
    depguard:
      rules:
        main:
          allow: ["$gostd"]
          files: ["internal/*.go"]

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
