// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AssetClass defines model for AssetClass.
type AssetClass struct {
	// Description Example: Public stocks, ETFs, and index funds
	Description string `json:"description"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id openapi_types.UUID `json:"id"`

	// Name Example: Equities
	Name string `json:"name"`
}

// AssetClassInput defines model for AssetClassInput.
type AssetClassInput struct {
	// Description Example: Public stocks, ETFs, and index funds
	Description string `json:"description"`

	// Name Example: Equities
	Name string `json:"name"`
}

// CurrentUserResponse defines model for CurrentUserResponse.
type CurrentUserResponse struct {
	// Email Example: user@example.com
	Email openapi_types.Email `json:"email"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id openapi_types.UUID `json:"id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Example: email already registered
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Email Example: user@example.com
	Email openapi_types.Email `json:"email"`

	// Password Example: secureP@ss123
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Email Example: user@example.com
	Email openapi_types.Email `json:"email"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id openapi_types.UUID `json:"id"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	// Status Example: ok
	Status string `json:"status"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Example: user@example.com
	Email openapi_types.Email `json:"email"`

	// Password Example: secureP@ss123
	Password string `json:"password"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	// Email Example: user@example.com
	Email openapi_types.Email `json:"email"`

	// Id Example: 550e8400-e29b-41d4-a716-446655440000
	Id openapi_types.UUID `json:"id"`
}

// SystemStatusResponse defines model for SystemStatusResponse.
type SystemStatusResponse struct {
	// NeedsSetup Whether the system needs initial setup. True when no users exist.
	//
	// Example: true
	NeedsSetup bool `json:"needsSetup"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Field Example: email
	Field string `json:"field"`

	// Message Example: email is required
	Message string `json:"message"`
}

// ValidationErrors defines model for ValidationErrors.
type ValidationErrors struct {
	Errors []ValidationError `json:"errors"`
}

// CreateAssetJSONRequestBody defines body for CreateAsset for application/json ContentType.
type CreateAssetJSONRequestBody = AssetClassInput

// UpdateAssetJSONRequestBody defines body for UpdateAsset for application/json ContentType.
type UpdateAssetJSONRequestBody = AssetClassInput

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAssets List asset classes
	// (GET /assets)
	ListAssets(w http.ResponseWriter, r *http.Request)
	// CreateAsset Create an asset class
	// (POST /assets)
	CreateAsset(w http.ResponseWriter, r *http.Request)
	// DeleteAsset Delete an asset class
	// (DELETE /assets/{id})
	DeleteAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetAsset Get an asset class
	// (GET /assets/{id})
	GetAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateAsset Update an asset class
	// (PATCH /assets/{id})
	UpdateAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Ping Server health check
	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request)
	// SystemStatus Check if the system needs initial setup
	// (GET /setup/status)
	SystemStatus(w http.ResponseWriter, r *http.Request)
	// CurrentUser Get the current authenticated user
	// (GET /users/current-user)
	CurrentUser(w http.ResponseWriter, r *http.Request)
	// Login Authenticate a user
	// (POST /users/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Log out a user
	// (POST /users/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Register Register a new user
	// (POST /users/register)
	Register(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListAssets List asset classes
// (GET /assets)
func (_ Unimplemented) ListAssets(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateAsset Create an asset class
// (POST /assets)
func (_ Unimplemented) CreateAsset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteAsset Delete an asset class
// (DELETE /assets/{id})
func (_ Unimplemented) DeleteAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAsset Get an asset class
// (GET /assets/{id})
func (_ Unimplemented) GetAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateAsset Update an asset class
// (PATCH /assets/{id})
func (_ Unimplemented) UpdateAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ping Server health check
// (GET /ping)
func (_ Unimplemented) Ping(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemStatus Check if the system needs initial setup
// (GET /setup/status)
func (_ Unimplemented) SystemStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CurrentUser Get the current authenticated user
// (GET /users/current-user)
func (_ Unimplemented) CurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login Authenticate a user
// (POST /users/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Log out a user
// (POST /users/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register Register a new user
// (POST /users/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAssets operation middleware
func (siw *ServerInterfaceWrapper) ListAssets(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAssets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAsset operation middleware
func (siw *ServerInterfaceWrapper) CreateAsset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAsset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAsset operation middleware
func (siw *ServerInterfaceWrapper) DeleteAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAsset operation middleware
func (siw *ServerInterfaceWrapper) UpdateAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemStatus operation middleware
func (siw *ServerInterfaceWrapper) SystemStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CurrentUser operation middleware
func (siw *ServerInterfaceWrapper) CurrentUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets", wrapper.ListAssets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets", wrapper.CreateAsset)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/assets/{id}", wrapper.DeleteAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}", wrapper.GetAsset)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/assets/{id}", wrapper.UpdateAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.Ping)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/setup/status", wrapper.SystemStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/current-user", wrapper.CurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/login", wrapper.Login)
	})

	return r
}

type ListAssetsRequestObject struct {
}

type ListAssetsResponseObject interface {
	VisitListAssetsResponse(w http.ResponseWriter) error
}

type ListAssets200JSONResponse []AssetClass

func (response ListAssets200JSONResponse) VisitListAssetsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAssets401JSONResponse ErrorResponse

func (response ListAssets401JSONResponse) VisitListAssetsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAssetRequestObject struct {
	Body *CreateAssetJSONRequestBody
}

type CreateAssetResponseObject interface {
	VisitCreateAssetResponse(w http.ResponseWriter) error
}

type CreateAsset201JSONResponse AssetClass

func (response CreateAsset201JSONResponse) VisitCreateAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAsset401JSONResponse ErrorResponse

func (response CreateAsset401JSONResponse) VisitCreateAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAsset422JSONResponse ValidationErrors

func (response CreateAsset422JSONResponse) VisitCreateAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAssetRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteAssetResponseObject interface {
	VisitDeleteAssetResponse(w http.ResponseWriter) error
}

type DeleteAsset204Response struct {
}

func (response DeleteAsset204Response) VisitDeleteAssetResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAsset401JSONResponse ErrorResponse

func (response DeleteAsset401JSONResponse) VisitDeleteAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAsset404JSONResponse ErrorResponse

func (response DeleteAsset404JSONResponse) VisitDeleteAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetAssetRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetAssetResponseObject interface {
	VisitGetAssetResponse(w http.ResponseWriter) error
}

type GetAsset200JSONResponse AssetClass

func (response GetAsset200JSONResponse) VisitGetAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAsset401JSONResponse ErrorResponse

func (response GetAsset401JSONResponse) VisitGetAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetAsset404JSONResponse ErrorResponse

func (response GetAsset404JSONResponse) VisitGetAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAssetRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateAssetJSONRequestBody
}

type UpdateAssetResponseObject interface {
	VisitUpdateAssetResponse(w http.ResponseWriter) error
}

type UpdateAsset200JSONResponse AssetClass

func (response UpdateAsset200JSONResponse) VisitUpdateAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAsset401JSONResponse ErrorResponse

func (response UpdateAsset401JSONResponse) VisitUpdateAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAsset404JSONResponse ErrorResponse

func (response UpdateAsset404JSONResponse) VisitUpdateAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateAsset422JSONResponse ValidationErrors

func (response UpdateAsset422JSONResponse) VisitUpdateAssetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

type Ping200JSONResponse PingResponse

func (response Ping200JSONResponse) VisitPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SystemStatusRequestObject struct {
}

type SystemStatusResponseObject interface {
	VisitSystemStatusResponse(w http.ResponseWriter) error
}

type SystemStatus200JSONResponse SystemStatusResponse

func (response SystemStatus200JSONResponse) VisitSystemStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CurrentUserRequestObject struct {
}

type CurrentUserResponseObject interface {
	VisitCurrentUserResponse(w http.ResponseWriter) error
}

type CurrentUser200JSONResponse CurrentUserResponse

func (response CurrentUser200JSONResponse) VisitCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CurrentUser401JSONResponse ErrorResponse

func (response CurrentUser401JSONResponse) VisitCurrentUserResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie *string
}

type Login200JSONResponse struct {
	Body    LoginResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login422JSONResponse ValidationErrors

func (response Login422JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201ResponseHeaders struct {
	SetCookie *string
}

type Register201JSONResponse struct {
	Body    RegisterResponse
	Headers Register201ResponseHeaders
}

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse ErrorResponse

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register422JSONResponse ValidationErrors

func (response Register422JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListAssets List asset classes
	// (GET /assets)
	ListAssets(ctx context.Context, request ListAssetsRequestObject) (ListAssetsResponseObject, error)
	// CreateAsset Create an asset class
	// (POST /assets)
	CreateAsset(ctx context.Context, request CreateAssetRequestObject) (CreateAssetResponseObject, error)
	// DeleteAsset Delete an asset class
	// (DELETE /assets/{id})
	DeleteAsset(ctx context.Context, request DeleteAssetRequestObject) (DeleteAssetResponseObject, error)
	// GetAsset Get an asset class
	// (GET /assets/{id})
	GetAsset(ctx context.Context, request GetAssetRequestObject) (GetAssetResponseObject, error)
	// UpdateAsset Update an asset class
	// (PATCH /assets/{id})
	UpdateAsset(ctx context.Context, request UpdateAssetRequestObject) (UpdateAssetResponseObject, error)
	// Ping Server health check
	// (GET /ping)
	Ping(ctx context.Context, request PingRequestObject) (PingResponseObject, error)
	// SystemStatus Check if the system needs initial setup
	// (GET /setup/status)
	SystemStatus(ctx context.Context, request SystemStatusRequestObject) (SystemStatusResponseObject, error)
	// CurrentUser Get the current authenticated user
	// (GET /users/current-user)
	CurrentUser(ctx context.Context, request CurrentUserRequestObject) (CurrentUserResponseObject, error)
	// Login Authenticate a user
	// (POST /users/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Log out a user
	// (POST /users/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Register Register a new user
	// (POST /users/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListAssets operation middleware
func (sh *strictHandler) ListAssets(w http.ResponseWriter, r *http.Request) {
	var request ListAssetsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAssets(ctx, request.(ListAssetsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAssets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAssetsResponseObject); ok {
		if err := validResponse.VisitListAssetsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAsset operation middleware
func (sh *strictHandler) CreateAsset(w http.ResponseWriter, r *http.Request) {
	var request CreateAssetRequestObject

	var body CreateAssetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAsset(ctx, request.(CreateAssetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAsset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAssetResponseObject); ok {
		if err := validResponse.VisitCreateAssetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAsset operation middleware
func (sh *strictHandler) DeleteAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteAssetRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAsset(ctx, request.(DeleteAssetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAsset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAssetResponseObject); ok {
		if err := validResponse.VisitDeleteAssetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAsset operation middleware
func (sh *strictHandler) GetAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetAssetRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAsset(ctx, request.(GetAssetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAsset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAssetResponseObject); ok {
		if err := validResponse.VisitGetAssetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAsset operation middleware
func (sh *strictHandler) UpdateAsset(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateAssetRequestObject

	request.Id = id

	var body UpdateAssetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAsset(ctx, request.(UpdateAssetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAsset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAssetResponseObject); ok {
		if err := validResponse.VisitUpdateAssetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Ping operation middleware
func (sh *strictHandler) Ping(w http.ResponseWriter, r *http.Request) {
	var request PingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Ping(ctx, request.(PingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ping")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PingResponseObject); ok {
		if err := validResponse.VisitPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemStatus operation middleware
func (sh *strictHandler) SystemStatus(w http.ResponseWriter, r *http.Request) {
	var request SystemStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemStatus(ctx, request.(SystemStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemStatusResponseObject); ok {
		if err := validResponse.VisitSystemStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CurrentUser operation middleware
func (sh *strictHandler) CurrentUser(w http.ResponseWriter, r *http.Request) {
	var request CurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CurrentUser(ctx, request.(CurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CurrentUserResponseObject); ok {
		if err := validResponse.VisitCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpvb9vI8f4qA/5+QB2UluSck+YUHHCu7Mv5zo1dK+69uASHFTkiN17u8HaHstVAQF/1AxT9hPdJit2l",
	"JFJi/Ae9OAnSd/qz3J2Z59lnZof7LkqoKEmjZhsN30U2ybEQ/uOBtcgjJaz/JtJUsiQt1JmhEg1LtNFw",
	"KpTFOCobP72LUrSJkaUb7b7itShKhdEwOqsmSiZgmZJLG8PRq+9sDEKnIHWK1zCtdGqjOOJ56UZbNlJn",
	"0SKOZNqe58mTAT7bHwx28fHXk939vXR/V/xp7+nu/v7Tp0+e7O8PBoNBFEdTMoXgaBhVlUy75tWiwPbM",
	"R79W0rsRR4XUJ6gzzqPh3tazizgy+GslDabR8OfIT+9ni1vev1k9SJO3mLBbdB3WY11W/LFj+7vF4I7u",
	"jypjUPOFRXOOtiRt8Z4hwEJI1Ta5smi+rb/2Eiqa4IfhD8aqLmYEE7qicWQMteLQdrVAa0W2gY+fDYQy",
	"KNI5GMykZXTL3WbLcrYuQ04ok/ocf63Q8kfCoxTWXpHZQMViUhk8+9bavcdftSn57DaHl0utZr7B8y+e",
	"imdSZ+9nomXBlW1bSZe3rlk/1rXeeU3cL5J0a+e/eN6N55axGHuivJ9/GjG1Y+Sq3MqC0U85co4GOEew",
	"fjbww0FqyVIosO65HrwyFcJVjho0gYuXBbyWlnvOvmUM2FS4snJCpFDo7Vy3tqbLpb8JJVPhrPP6vu3N",
	"VKJKO1S9C6MbcoC0sLLqNhTCkvGNSWDDbrttOK5+l4yF//D/BqfRMPq//rqQ7NdVZH8zEIvVosIYMd/e",
	"O2H6bdvcQLxmNFqoQ0q2S6HozJAbCjkVWIoMfe2TUlIVqNmbEMVRZVQ0jHLm0g77/UxyXk3cZum/FaYg",
	"u2uF7gvDubwUfnvoKbmVEtIsEm7svOVP34YHeynOlhXgMBpTYcRbGItcbK3ZGL+IN1w4CCs7WAWUZHhK",
	"ShKwEcml1BmIslQy8b7ApJKK4UpyDi+o91q/yhEOzo5hSkrRlZtAibmrCkCYJJeMCVcGYed7oVOFBn77",
	"579gjGYmE/Sfz7EkK5nM/FGYdZRLMFSx1FkM47+eSEYo0VgnWzrBGCybyk+awg/j05egKMuclTMpwCrK",
	"QvXp/ho6w0y9tSGIB+w0vOnPdNoTpfzjW0v6kduOSiZY60Ad1BcvL+BgOkVD8AI1GqGgLnlPwliYfdUb",
	"3A/j/kTRpF8Iqfsnx6Ojl+Mjz1A0hT2d1tFpzFU/1Vtj2Pdjd2m6a+vRccSS/RZdonlwdhzF0cyFzqM8",
	"6O31Bm4dKlGLUkbD6KvewJteCs49tfvCHRL8xwx5m+znyJXRFoRS4IdC4g4UaANZMIXJ3MthEqptr3Y9",
	"OA9bzYKoOEfNdfhdwN0m91+O02gYnUjLB8EEt0EDct6cx4PBckegDkm7gaPDb32KvLNMNE6a2wqxtU1O",
	"f3Sj9gd79zLkpvXbVXjHkhfaRYyM/Dum8Ns//u0SyMxpG1i0Hlf3jK2KQph5Hb82MI4YIrNO5Ly3MKp/",
	"f+OKELIdII8MCnZggcar5mxhgzp4Mzlz2UwUtdytn78H2GEdb1UU5Bgt/5nS+e8W380j76Kt+y7lLrZ4",
	"tvcBlu/C9qAR2MSHIv0U+RVH+48f/24WbWX6TqNKQ4krFyYKwTGI59642ephwJDWW+QPfAKhm5y9gf+L",
	"eKl3/XcyXYSNoJCxS/cKmjlKt+Z2Ynd8eA/GH/rpl4wvhREFMrq65ud3kXQLOSVeJ3Rfwbb5GjcCfVs5",
	"/GaL2/vbrjVpGNz/VGkYrH8Yi14Sw5QqvTKnQwalhePDDQ4GhO/OwfiWPAtW6kzhf8W6F8gfkXKDB5LT",
	"TzM7fya0fYF8H86WgpO8i7WlEokrBnPsLA6AphvL3IPGF2UqHlo8P5GSZPARSpLKh/t/ueBem+rzKZbC",
	"brpfsVS6nXHr0RBC7xVKMVckUmCChPRUmiI0ytDM0PgWUqW1by/oFESSYOnO/FBvOtuDCxvOk36WiVBC",
	"J2hsDAVpyeS2KTCRsrCDvawXw0XJssBzmhDHcGaoQM6xso9CQ2B03B8dQo5CcQ5Jjsml7cFL2pCdVV/L",
	"CZOjRFpD/O513VN+HQ3hdUSXr6MFkAZbJS7623J15oL1AXdyq23+nnzYQnwcAt+MQAPv0A2tgfZ9y/66",
	"9X4j4FeNLmizU2SWwj6VxvKuwyY0RGFH9rAXbzRDYY78aA26m21qfKA8hVJMZIrrxQhsTld+WHgTFUIP",
	"ZEBRJjWUIsMbAd5CrNkQ/pDIdTae74LgyGEGcnpLw/l9qPpg9+vOzK77diu2jVaOmjcjianH7g9O9vz2",
	"8v3JZjavRds98wvTJWr4nrk81WoOCdGl9GSAtPL7OEBGpoVlR8dg/Q73QwLU9aq4A59Ro8cFvmX7qbeH",
	"XJnX7M5tA9rgjnPftqjjUfK9+c6+UZ2u6vqvpkf90linsHwvBYnB1K0qlO3B6UpCY3/ayTSm8MNPr1yC",
	"cAQR/tC9SZ2ZFH6RMfLuKPyUo0jR9OCVV4S65zuh1D2jWciazXficCD//mAPpmRgQpxDpS81XemGP1eG",
	"dLb2ignEjGQKCoXvml/lMskbzjqPpE7IGEy4o/Xpg/this7WS/YHrjjbr7m7is62PtdsmFYqiqMAqrdp",
	"DfU28zbpUSPuKwQnlStW9aBmi2A2clIx2uGKXM9h7F+/wo6vV7LK+JrKcW10evrj8dEv46PRxfkRoJ7B",
	"TJhHz2EsChxLxm9OxPVzOBOcf9N/Dn8R17sHGX7z7On+YOCQXkdq85Sx+OiSIXVQjEBsMitGf07VbIND",
	"COJOSkbhCtR7WuAKhdkSDLd6YFiQGSdTxsVN21p2K81SgWQLWnBlhAK8LqWZw6Rit/81gSKdoQHr9Hf5",
	"skRJ1N2S4Ky8SxfvhLIMU6CKGxtIzTdfD1Dmh9whQsvrPTfEqPWawCdBkSRUad58T7CdA0L8VtopLeTC",
	"5q7ywykZBMtkfP3WTA/LrOKFtCgwlYJxsywZPkgW0Xjlpgld+84ssgXm8ubFB5L4zVstD/yqY+teSdfm",
	"dtgtY+YPfU3gvhy1//rh1H5Eeqpkwl5D33t/7zMS+iXPGqrTJWPuGX/cDd3BzcONEixnCBNhnQhxDqXB",
	"EnWKoYxTyl9pMOQYE7RAJFwJBTlZDkJGhkEYhCV5HKUZUiwVzQun7f68u1SYg8PDc0ckaUj7f2fCSO/6",
	"TopTUSmG4bPBYODvIISLBH1RymjxZuXcphdHOi1Jara+RpV6asTqZkSjRRK3Wx6hF7JSJqFgJq2cSCV5",
	"7j21WPvtvat0u14O93o5hGrqz9rt3gyZJMfVYbxUgqdkCgs7P1YTNBrdxKWhCS7bMsvLNVD57s3Sct9Q",
	"WV5rCYfYRXxzCFoZqBBaZOhCHbuiW1Vp6C2tT5fxRmYP5pSGplLhOkJNQwK9brPDL+37Wq0LEo7cjgpM",
	"5a7CGSpwIc3ISKw7WLC8AB3Dd/IaU39aKDCGkZmXTI+ch56gmaGqhJyUc6ppYLtpt3iz+E8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
