name: SQL Validation

on:
  pull_request:
    paths:
      - "server/db/**/*.sql"
      - "server/sqlc.yaml"
    branches: [main]

jobs:
  check:
    name: SQL Validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v7.0.0

      - name: Setup Golang
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: ./server/go.mod
          cache: true
          cache-dependency-path: ./server/go.sum

      - name: Install sqlc
        uses: sqlc-dev/setup-sqlc@v5.0.0
        with:
          sqlc-version: 1.31.1

      - name: Lint SQL Statements
        run: sqlc vet

      - name: Ensure Generated Go Code is Updated
        run: sqlc diff
